### PR TITLE
fix(ComboBox): Use latest value of `onChange` prop

### LINKED ISSUE #635: Combobox onChange doesn't honor updated dependencies
#### Describe the bug (actual behavior)
When dependencies change in the `useCallback()` , combobox doesn't honor this update.

#### Expected behavior
Combobox onChange should use the updated dependencies.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/combobox-onchange-noformik-t55umm?file=/src/App.tsx

##### Steps to reproduce
1. Select a skill in Combobox skill.
1. Verify skill is set.
1. Select the same skill.

Expected Result: It should show the alert that the user selected the same skill.
Actual Result: It re-sets the skill.

##### Additional information:
Didn't check if `onBlur` behaves the same way or not.

### PR DESCRIPTION
**Pull request by mayank99**
Previously, the ref was locked to the very initial value of `onChange`. The useEffect ensures that we get the latest value.

Fixes #635.

## Checklist

- [x] Add meaningful unit tests for your component (verify that all lines are covered)
- [x] Verify that all existing tests pass
- [x] ~Add component features demo in Storybook (different stories)~
- [x] ~Approve test images for new stories~
- [x] ~Add screenshots of the key elements of the component~

### CODE REVIEW

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -190,9 +193,8 @@ export const ComboBox = <T,>(props: ComboBoxProps<T>) => {
   );
 
   // Maintain internal selected value state synced with `value` prop
-  const [selectedValue, setSelectedValue] = React.useState<T | undefined>(
-    value,
-  );
+  const [selectedValue, setSelectedValue] =
+    React.useState<T | undefined>(value);
```
Comment (veekeys) [inline packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:197]: weird

**Review by veekeys — APPROVED** [review]

**Review by adamhock — APPROVED** [review]

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 1 above)
Comment (mayank99) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:197]: Yeah it must be from a different version of prettier. Idk why it didn't change in the monorepo PR
