### PR TITLE
fix(Table): Horizontal scroll is working when virtual scroll is enabled

### LINKED ISSUE #676: Virtualization disables horizontal scroll
#### Describe the bug (actual behavior)
When virtualization is enabled and table is wider than its parent, no horizontal scroll is enabled.

#### Expected behavior
Horizontal scroll should be visible and the table should be scrollable.

#### Reproduction
https://codesandbox.io/s/itwinui-react-minimal-example-forked-p1q6ih?file=/src/App.tsx

#### Additional information
VirtualScroll sets div style to `overflow: 'hidden'`, which causes the issue.

### PR DESCRIPTION
**Pull request by bentleyvk**
Closes #676 

`overflow: hidden` on outer div seems to do nothing, kind of obvious because it also has `minHeight` of the full list.
So removing it, seems to fix the issue.

## Checklist

- [x] ~Add meaningful unit tests for your component (verify that all lines are covered)~
- [x] Verify that all existing tests pass
- [x] ~Add component features demo in Storybook (different stories)~
- [x] Approve test images for new stories
- [x] ~Add screenshots of the key elements of the component~

### CODE REVIEW

File: packages/iTwinUI-react/src/core/utils/components/VirtualScroll.tsx [hunk 1]
```diff
@@ -389,14 +389,13 @@ export const useVirtualization = (props: VirtualScrollProps) => {
   return {
     outerProps: {
       style: {
-        overflow: 'hidden',
```
Comment (mayank99) [inline packages/iTwinUI-react/src/core/utils/components/VirtualScroll.tsx:392]: I'm not sure about this change.

@veekeys Do you remember why this was added?

Comment (veekeys) [reply packages/iTwinUI-react/src/core/utils/components/VirtualScroll.tsx:392]: I was trying to find the case, but could not.. So I am not sure anymore :/

**Review by mayank99 — APPROVED** [review]

**Review by gretanausedaite — APPROVED** [review]
🌵
