### PR TITLE
fix(Menu): Fixed keyboard navigation when MenuItem contains selectable children

### LINKED ISSUE #379: Menu: When `MenuItem` has actionable elements, arrow navigation is going trough them
When `MenuExtraContent` has actionable elements, arrow navigation is going trough them.
Need to only allow arrow navigation through menu items.

### PR DESCRIPTION
**Pull request by bentleyvk**
Keyboard navigation goes trough each focusable item that has not focusable parent (omit inner focusable content like checkbox, anchor).

Closes #379 

## Checklist

- [x] Add meaningful unit tests for your component (verify that all lines are covered)
- [x] Verify that all existing tests pass
- [x] ~Add component features demo in Storybook (different stories)~
- [x] ~Approve test images for new stories~
- [x] ~Add screenshots of the key elements of the component~

### CODE REVIEW

File: src/core/Menu/Menu.tsx [hunk 1]
```diff
@@ -56,8 +56,16 @@ export const Menu = React.forwardRef<HTMLUListElement, MenuProps>(
       setFocusedIndex(null);
     }, [children]);
 
+    const getFocusableNodes = React.useCallback(() => {
+      const focusableItems = getFocusableElements(menuRef.current);
+      // Filter out focusable elements that are inside each node, e.g. checkbox, anchor
```
Comment (mayank99) [inline src/core/Menu/Menu.tsx:61]:
```suggestion
      // Filter out focusable elements that are inside each menu item, e.g. checkbox, anchor
```

File: src/core/Menu/Menu.test.tsx [hunk 2]
```diff
@@ -86,16 +102,27 @@ it('should handle keyboard navigation', () => {
   // Should skip separator and disabled item
```
Comment (mayank99) [inline src/core/Menu/Menu.test.tsx:102]:
```suggestion
  // Should skip checkbox, separator and disabled item
```

**Review by mayank99 — APPROVED** [review]
