### PR TITLE
fix(Table): Prevents crashing when clearing editable cell

### LINKED ISSUE #703: Table: Crash when leaving empty editable cell
#### Describe the bug (actual behavior)
Crash when using "tab" key or mouse click to leave a empty editable cell

**Note:  Working in Firefox, Crashing in Chrome**

#### Reproduction
Use story book "editable" example

##### Steps to reproduce
1. Enter "Description1" cell
2. Remove its content
3. Press "Tab" key or click outside to leave the cell

### PR DESCRIPTION
**Pull request by bentleyvk**
Closes #703  

Error was throw because when clearing editable cell, text node is being removed and React doesn't like DOM manipulation outside React. So giving editable cell a new key will make React reattach with the cell element in the DOM and it won't complain.

## Checklist

- [x] Add meaningful unit tests for your component (verify that all lines are covered)
- [x] Verify that all existing tests pass
- [x] ~Add component features demo in Storybook (different stories)~
- [x] ~Approve test images for new stories~
- [x] ~Add screenshots of the key elements of the component~

### CODE REVIEW

File: packages/iTwinUI-react/src/core/Table/cells/EditableCell.tsx [hunk 1]
```diff
@@ -80,6 +84,9 @@ export const EditableCell = <T extends Record<string, unknown>>(
           onCellEdit(cellProps.column.id, value, cellProps.row.original);
         }
         props.onBlur?.(e);
+        // Prevents error when text is cleared.
+        // New key makes React to reattach with the DOM so it won't complain about deleted text node.
+        setKey(getRandomValue(10));
```
Comment (mayank99) [inline packages/iTwinUI-react/src/core/Table/cells/EditableCell.tsx:89]: So I know React treats new key as a new node but why does this fix the error? Any reading material on this?

**Review by mayank99 — APPROVED** [review]
Interesting fix but works so LGTM 👍

File: packages/iTwinUI-react/src/core/Table/cells/EditableCell.tsx (hunk 1 above)
Comment (bentleyvk) [reply packages/iTwinUI-react/src/core/Table/cells/EditableCell.tsx:89]: I found about this here: https://stackoverflow.com/a/67686478/18045303

**Review by gretanausedaite — APPROVED** [review]
