### PR TITLE
Fix Slider bug where onChange was not always called after pointerUp

### LINKED ISSUE #221: Slider does not fire onChange event when last pointerMove value matches pointerUp value
#### Describe the bug (actual behavior)
When using new Slider in iModeljs, I found that the Slider does not fire its onChange event when last pointerMove value matches pointerUp value.

#### Expected behavior
onChange event should always be triggered on pointerUp event for slider.

#### Reproduction
Link to a minimal repro: 

##### Steps to reproduce
1. click on slider thumb
2. move thumb
3. release mouse button
4. notice onChange callback is not always fired

### PR DESCRIPTION
**Pull request by bsteinbk**
- Fix bug where pointerUp did not trigger onChange processing when pointerUp matches last pointerMove position. 
- Add Arrow Up/Down support to mimic Arrow Right/Left processing
- Improve eventlistener registration by using new `useEventListener` hook.

Closes #221

## Checklist

- [ ] Add meaningful unit tests for your component (verify that all lines are covered)
- [x] Verify that all existing tests pass
- [ ] Add component features demo in Storybook (different stories)
- [ ] Approve test images for new stories
- [ ] Add an entry to the changelog for any new components and changes
- [ ] Add screenshots of the key elements of the component
- [x] Add any additional comments describing the features you've implemented

### CODE REVIEW

File: src/core/Slider/Slider.tsx [hunk 1]
```diff
@@ -12,6 +12,47 @@ import { getBoundedValue } from '../utils/common';
 import { Track } from './Track';
 import { Thumb } from './Thumb';
 
+// based on https://usehooks.com/useEventListener/
+function usePointerEventListener(
```
Comment (mayank99) [inline src/core/Slider/Slider.tsx:16]: This could be a generic hook under `utils/`. There is no PointerEvent-specific logic here.

File: src/core/Slider/Slider.tsx [hunk 2]
```diff
@@ -12,6 +12,47 @@ import { getBoundedValue } from '../utils/common';
...
+  handler: (event: PointerEvent) => void,
+  element: HTMLElement | Document | undefined,
+) {
+  // Create a ref that stores handler
+  const savedHandler = React.useRef<(event: PointerEvent) => void>();
+
+  // Update ref.current value if handler changes.
+  // This allows our effect below to always get latest handler ...
+  // ... without us needing to pass it in effect deps array ...
+  // ... and potentially cause effect to re-run every render.
```
Comment (mayank99) [inline src/core/Slider/Slider.tsx:27]: This comment can be shortened and combined with the comment above.

File: src/core/Slider/Slider.tsx [hunk 3]
```diff
@@ -12,6 +12,47 @@ import { getBoundedValue } from '../utils/common';
...
+    savedHandler.current = handler;
+  }, [handler]);
+
+  React.useEffect(
+    () => {
+      // Make sure element supports addEventListener
+      const isSupported = element && element.addEventListener;
+      if (!isSupported) {
+        return;
+      }
```
Comment (mayank99) [inline src/core/Slider/Slider.tsx:38]: Is this needed? https://caniuse.com/addeventlistener

Could just do:
```suggestion
      if (!element) {
        return;
      }
```

File: src/core/Slider/Slider.tsx [hunk 4]
```diff
@@ -12,6 +12,47 @@ import { getBoundedValue } from '../utils/common';
...
+      const eventListener = (event: PointerEvent) =>
+        savedHandler.current?.(event);
+
+      // Add event listener
+      element?.addEventListener(eventName, eventListener);
+
+      // Remove event listener on cleanup
+      return () => {
+        element?.removeEventListener(eventName, eventListener);
+      };
```
Comment (mayank99) [inline src/core/Slider/Slider.tsx:50]: This could be simplified:
```suggestion
      element?.addEventListener(eventName, savedHandler.current);
      return () => element?.removeEventListener(eventName, savedHandler.current);
```

Or does that not work?

File: src/core/Slider/Slider.tsx [hunk 5]
```diff
@@ -272,6 +313,7 @@ export const Slider = React.forwardRef<HTMLDivElement, SliderProps>(
       (
         event: PointerEvent,
         callback?: (values: ReadonlyArray<number>) => void,
+        skipValueChangeCheck?: boolean,
```
Comment (mayank99) [inline src/core/Slider/Slider.tsx:316]: Where will this be false?

File: src/core/Slider/Thumb.tsx [hunk 6]
```diff
@@ -90,9 +90,11 @@ export const Thumb = (props: ThumbProps) => {
       }
       switch (event.key) {
         case 'ArrowLeft':
+        case 'ArrowDown':
           onThumbValueChanged(index, Math.max(value - step, minVal));
           return;
         case 'ArrowRight':
+        case 'ArrowUp':
```
Comment (mayank99) [inline src/core/Slider/Thumb.tsx:97]: Not sure about this change. Up is not the same as Right, and Down is not the same as Left.

**Review by mayank99 — COMMENTED** [review]
Thanks for the PR.

Could you also create an issue to link to this PR? Doesn't need to be fully detailed, it's just to help us track tasks.

File: src/core/Slider/Thumb.tsx (hunk 6 above)
Comment (bsteinbk) [reply src/core/Slider/Thumb.tsx:97]: These new arrow cases were added to mimic what was supported in react-compound-slider. I actually ran into a unit test that used the down arrow to move thumb to left (ie lower the thumb value).

File: src/core/Slider/Slider.tsx (hunk 1 above)
Comment (bsteinbk) [reply src/core/Slider/Slider.tsx]: I did move it to utils/hook/usePointerEventListener,  but the handler type is 'PointerEvent-specific'

Comment (mayank99) [reply src/core/Slider/Slider.tsx]: Yeah I'm saying make it a generic `useEventListener`

File: src/core/Slider/Thumb.tsx (hunk 6 above)
Comment (mayank99) [reply src/core/Slider/Thumb.tsx:97]: Okay, I checked the native slider and W3 variant and they both use Up/Down too, so this is fine.

I would add return early if `altKey` is pressed though. See example in https://github.com/iTwin/iTwinUI-react/blob/main/src/core/Menu/MenuItem.tsx#L107

File: src/core/Slider/Slider.tsx (hunk 4 above)
Comment (mayank99) [reply src/core/Slider/Slider.tsx]: Okay I think see the reasoning now (from the original source): https://overreacted.io/making-setinterval-declarative-with-react-hooks/#refs-to-the-rescue

I would still remove those redundant comments at least.

File: src/core/Slider/Slider.tsx (hunk 2 above)
Comment (bsteinbk) [reply src/core/Slider/Slider.tsx]: comments combined

File: src/core/Slider/Slider.tsx (hunk 1 above)
Comment (bsteinbk) [reply src/core/Slider/Slider.tsx]: I should have done this initially... done now.

File: src/core/Slider/Slider.tsx (hunk 3 above)
Comment (bsteinbk) [reply src/core/Slider/Slider.tsx]: updated

File: src/core/Slider/Slider.tsx (hunk 4 above)
Comment (bsteinbk) [reply src/core/Slider/Slider.tsx]: comments removed

File: src/core/Slider/Slider.tsx (hunk 5 above)
Comment (bsteinbk) [reply src/core/Slider/Slider.tsx]: renamed `skipValueChangeCheck` to `forceCallbackToRun`

File: src/core/Slider/Thumb.tsx (hunk 6 above)
Comment (bsteinbk) [reply src/core/Slider/Thumb.tsx:100]: done

**Review by mayank99 — APPROVED** [review]
LGTM!

Would still like @veekeys or @bentleyvk to review this before merging.

File: src/core/Slider/Thumb.tsx [hunk 7]
```diff
@@ -88,11 +88,16 @@ export const Thumb = (props: ThumbProps) => {
       if (disabled) {
```
Comment (veekeys) [inline src/core/Slider/Thumb.tsx:88]: Can add here `disabled || event.altKey`. Will save few lines

File: src/core/Slider/Slider.tsx [hunk 8]
```diff
@@ -323,7 +328,7 @@ export const Slider = React.forwardRef<HTMLDivElement, SliderProps>(
 
     const handlePointerUp = React.useCallback(
       (event: PointerEvent) => {
-        updateThumbValue(event, onChange);
+        updateThumbValue(event, onChange, true);
```
Comment (veekeys) [inline src/core/Slider/Slider.tsx:331]: If you asked me, I do not think we should raise `onChange` event if the value did not change (for the sliding action, we have `onUpdate` which can inform user that something is happaening, if he cares). Usually if `onChange event is raised, you expect a change and some action, which I do not think here is the case.

Comment (bsteinbk) [reply src/core/Slider/Slider.tsx:331]: I disagree, because the move action changes the internal value(s) of the slider not the external value(s). This change is required to provide functionality equivalent to the react-compound-slider that was used in iModeljs.

Comment (veekeys) [reply src/core/Slider/Slider.tsx:331]: If you had value of 50 then you slided to somewhere and without releasing mouse came back to 50, why user should get event of onChange if value did not change at the end???

Comment (bsteinbk) [reply src/core/Slider/Slider.tsx:331]: As you move the internal array values are being changed maintaining the internal state. for example mouse down at 50 - move - 60 - move - 70 - move 50 - mouse up, the internal array as been updated 3 times. We do not setup an original array of values at mouse down to compare them to values at mouse up.

File: src/core/Slider/Thumb.tsx (hunk 7 above)
Comment (bsteinbk) [reply src/core/Slider/Thumb.tsx]: done

File: src/core/Slider/Slider.tsx (hunk 8 above)
Comment (veekeys) [reply src/core/Slider/Slider.tsx:331]: amm.. Ok, I am lost now. This code part does nothing internally:
` if (
            !forceCallbackToRun &&
            pointerValue === currentValues[activeThumbIndex]
          ) {
            return;
          }
          const newValues = [...currentValues];
          newValues[activeThumbIndex] = pointerValue;
          setCurrentValues(newValues);`

It basically sets new array of the same values as it was before (there is a check).
But if you force it, internally it goes through it + calls `onChange` to the user that something has changed (which I assume has not).

Comment (bsteinbk) [reply src/core/Slider/Slider.tsx:331]: You are right on that account ... I don't need to update the internal state array... but I do need to call the onChange... I can make that change.

Comment (bsteinbk) [reply src/core/Slider/Slider.tsx]: @veekeys I attempted to make the function processing more descriptive... hopefully I did.

File: src/core/Slider/Slider.tsx [hunk 9]
```diff
@@ -163,8 +163,8 @@ export type SliderProps = {
    */
   thumbProps?: (index: number) => React.HTMLAttributes<HTMLDivElement>;
   /**
-   * Callback fired when the value(s) of the slider has changed. This will receive
-   * changes at the end of a slide as well as changes from clicks on rails and tracks.
+   * Callback fired at the end of a thumb move and when there user clicks on rail
```
Comment (veekeys) [inline src/core/Slider/Slider.tsx:166]: maybe enough `and when user clicks on rail`? this 'there' does not give anything..does it?

Comment (mayank99) [reply src/core/Slider/Slider.tsx:166]: I think that's a typo 😆

Comment (mayank99) [reply src/core/Slider/Slider.tsx:166]: I was also gonna say, maybe we should explicitly mention `pointerUp` in this comment

Comment (bsteinbk) [reply src/core/Slider/Slider.tsx:166]: I wish I could use the excuse that English is my second language.

File: src/core/Slider/Slider.tsx [hunk 10]
```diff
@@ -284,28 +280,40 @@ export const Slider = React.forwardRef<HTMLDivElement, SliderProps>(
           pointerValue = roundValueToClosestStep(pointerValue, step, min);
           const [minVal, maxVal] = getAllowableThumbRange(activeThumbIndex);
           pointerValue = getBoundedValue(pointerValue, minVal, maxVal);
-          if (
-            !forceCallbackToRun &&
-            pointerValue === currentValues[activeThumbIndex]
-          ) {
+          if (pointerValue === currentValues[activeThumbIndex]) {
```
Comment (veekeys) [inline src/core/Slider/Slider.tsx:282]: `pointerValue === currentValues[activeThumbIndex] && 'onChange' === callbackType` but I am still thinking about the approach here...

Comment (bsteinbk) [reply src/core/Slider/Slider.tsx:282]: Not sure what you are asking for... I want to return for both callbackTypes, but I just want to fire callback if type is 'onChange'...
```
          if (pointerValue === currentValues[activeThumbIndex]) {
            if ('onChange' === callbackType) {
              onChange?.(currentValues);
            }
            return;
          }
```

**Review by veekeys — APPROVED** [review]
