### PR TITLE
fix(utils): MiddleTextTruncation responds to resize

### LINKED ISSUE #454: MiddleTextTruncation flex-grow bug
MiddleTextTruncation does not grow back when screen is resized from small to larger.

### PR DESCRIPTION
**Pull request by gretanausedaite**
MiddleTextTruncation now responds to resize.
Closes: #454

### CODE REVIEW

File: src/core/utils/components/MiddleTextTruncation.tsx [hunk 1]
```diff
@@ -47,6 +47,7 @@ export const MiddleTextTruncation = (props: MiddleTextTruncationProps) => {
       style={{
         display: 'flex',
         minWidth: 0,
+        flexGrow: 1,
```
Comment (mayank99) [inline src/core/utils/components/MiddleTextTruncation.tsx:50]: @veekeys Can you verify this is fine, since you implemented this component?

**Review by mayank99 — APPROVED** [review]
Looks good. PR title can be improved for changelog.

File: src/core/utils/components/MiddleTextTruncation.tsx (hunk 1 above)
Comment (veekeys) [reply src/core/utils/components/MiddleTextTruncation.tsx:50]: Yeah, it is needed.. It is weird, why I dont have it, cause i was sure I added it. But it worked well without it in select examples somehow though... Might be the case only with the elements size change, though..
