### PR TITLE
Fix for selecting filtered table

### LINKED ISSUE #222: Table: Crashes when selecting a row after filtering
##### Steps to reproduce

1. Select any checkbox 
2. Apply Filter 	
3. Again select any checkbox 	
4. Table component crash and throws exception.

image

### PR DESCRIPTION
**Pull request by bentleyvk**
Closes #222

- Preserving selected state even after filtering.
- Showing indeterminate state for filtered table header checkbox if there are selected rows that are filtered out.
- Added a story with all table features (except lazy-loading).

select_and_filter_fixed

## Checklist

- [x] Add meaningful unit tests for your component (verify that all lines are covered)
- [x] Verify that all existing tests pass
- [x] Add component features demo in Storybook (different stories)
- [x] Approve test images for new stories
- [x] Add an entry to the changelog for any new components and changes
- [x] Add screenshots of the key elements of the component
- [x] Add any additional comments describing the features you've implemented

### CODE REVIEW

File: src/types/react-table-config.ts [hunk 1]
```diff
@@ -89,7 +89,9 @@ declare module 'react-table' {
       UsePaginationInstanceProps<D>,
       UseRowSelectInstanceProps<D>,
       UseRowStateInstanceProps<D>,
-      UseSortByInstanceProps<D> {}
+      UseSortByInstanceProps<D> {
+    initialRows: Row<D>[];
+  }
```
Comment (mayank99) [inline src/types/react-table-config.ts:94]: Formatting messed up here?

File: src/core/Table/Table.tsx [hunk 2]
```diff
@@ -287,13 +287,11 @@ export const Table = <
...
             isRowDisabled?.(row.original),
           );
-          const checked =
-            instance.isAllRowsSelected ||
-            instance.rows.every(
-              (row) =>
-                instance.state.selectedRowIds[row.id] ||
-                isRowDisabled?.(row.original),
-            );
+          const checked = instance.initialRows.every(
```
Comment (mayank99) [inline src/core/Table/Table.tsx:290]: I can't find any info on `initialRows` in react-table docs. Do you have a link?

Comment (bentleyvk) [reply src/core/Table/Table.tsx:290]: There isn't. Just code:
https://github.com/tannerlinsley/react-table/blob/8ec25cabccf915991ec00cf67bfb26a83aa0c0b2/src/hooks/useTable.js#L213

File: src/types/react-table-config.ts (hunk 1 above)
Comment (bentleyvk) [reply src/types/react-table-config.ts:94]: Everything good here.

Comment (mayank99) [reply src/types/react-table-config.ts:94]: image

File: src/core/Table/Table.tsx (hunk 2 above)
Comment (mayank99) [reply src/core/Table/Table.tsx:290]: So it's a secret property that magically fixes our bug?

File: src/types/react-table-config.ts (hunk 1 above)
Comment (bentleyvk) [reply src/types/react-table-config.ts:94]: It is a property, not an extended interface/type.
image

File: src/core/Table/Table.tsx (hunk 2 above)
Comment (bentleyvk) [reply src/core/Table/Table.tsx:290]: Kind of. Typings come from different package so they might missed it.

File: src/types/react-table-config.ts (hunk 1 above)
Comment (mayank99) [reply src/types/react-table-config.ts:94]: Ohhh the braces are for the main interface, that's confusing lol

File: src/core/Table/Table.tsx (hunk 2 above)
Comment (mayank99) [reply src/core/Table/Table.tsx:290]: And did you narrow down why the crash was happening? Need to remove both `instance.rows` and `isAllRowsSelected`?

Comment (bentleyvk) [reply src/core/Table/Table.tsx:290]: Of course 😃 All selected rows are being saved to `selectedRowIds` even if table is filtered. Previously I was going through each selected row id and trying to get data from `rowsById` map. However, it only has filtered rows, so it tried to get `.original` from `undefined` row. 
I had to remove `isAllRowsSelected` because it is also checking only in `rowsById` map which is filtered and in order to achieve the same behavior as material-ui, I have to check each initial row.

**Review by mayank99 — APPROVED** [review]
