### PR TITLE
fix(ComboBox): Move max-height to outer element to fix virtual scroll

### LINKED ISSUE #984: ComboBox: broken layout when using virtualization
In v2, combobox with `enableVirtualization` looks broken. The menu takes up all the available height and doesn't scroll properly.

https://itwin.github.io/iTwinUI-react/?path=/story/core-combobox--virtualized
https://itwin.github.io/iTwinUI-react/iframe.html?args=&id=core-combobox--virtualized&viewMode=story

### PR DESCRIPTION
**Pull request by mayank99**
Virtualization broke after #840 because `maxHeight: 315` was removed from `Surface` (presumably because the max-height is specified in the css through `iui-menu.iui-scroll`). But that doesn't work, because for virtual scroll to work, the max-height must be on the outermost element.

This PR unsets the `Menu` max-height by removing `iui-scroll`, and manually adds the same max-height to the outermost element (`Surface`). Also adds a visual test for it to help catch any future regressions.

Unrelated: `elevation={1}` was removed from `Surface` because that's the default in css now.

### CODE REVIEW

File: packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx [hunk 1]
```diff
@@ -56,31 +56,27 @@ const VirtualizedComboBoxMenu = React.forwardRef(
...
-      >
+      <Surface style={surfaceStyles} {...rest}>
         <div {...outerProps}>
           <Menu
             id={`${id}-list`}
             setFocus={false}
             role='listbox'
             ref={mergeRefs(menuRef, innerProps.ref, forwardedRef)}
-            className={cx('iui-scroll', className)}
+            className={className}
```
Comment (rohan-kadkol) [inline packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx:79]: Just curious, would still using the `.iui-scroll` for `overlay-y` but just overriding the `max-height` remove the need for `isOverflowOverlaySupported`?

https://github.com/iTwin/iTwinUI/blob/9912acf9a0a526ccf34d1089ef03722ed26d5c62/packages/itwinui-css/src/menu/menu.scss#L30-L34

File: packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx [hunk 2]
```diff
@@ -56,31 +56,27 @@ const VirtualizedComboBoxMenu = React.forwardRef(
...
+      getWindow()?.CSS?.supports?.('overflow: overlay');
 
-    const styles = React.useMemo(
-      () => ({
-        minWidth,
-        maxWidth: `min(${minWidth * 2}px, 90vw)`,
-      }),
-      [minWidth],
-    );
+    const surfaceStyles = {
```
Comment (veekeys) [inline packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx:62]: you think component is too light to memoize this object?

File: packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx [hunk 3]
```diff
@@ -56,31 +56,27 @@ const VirtualizedComboBoxMenu = React.forwardRef(
       scrollToIndex: focusedVisibleIndex,
     });
 
-    const overflowY = getWindow()?.CSS?.supports?.('overflow-x: overlay')
-      ? { overflowY: 'overlay' }
-      : { overflowY: 'auto' };
+    const isOverflowOverlaySupported =
```
Comment (veekeys) [inline packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx:59]: to same comment, this could be moved outside the component code too

File: packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx (hunk 2 above)
Comment (mayank99) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx:62]: this object itself is not really expensive to create, so i dont think there's a need to memoize

File: packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx (hunk 3 above)
Comment (mayank99) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBoxMenu.tsx]: done

**Review by gretanausedaite — APPROVED** [review]
