### PR TITLE
fix(Combobox): Allow users to reset value

### LINKED ISSUE #697: ComboBox: Infinite loop
#### Describe the bug (actual behavior)
Externally changing the controlled value of the ComboBox is not respected or an infinite loop occurs. 

#### Reproduction
https://codesandbox.io/s/itwinui-react-example-forked-v8pllg?file=/src/App.tsx

### PR DESCRIPTION
**Pull request by gretanausedaite**
Fixes bug #697 

Removed line 273: Allow users to set value as undefined.
Removed line 275 (part of 280): Fix infinite loop bouncing between two useEffects.

### CODE REVIEW

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -151,6 +151,7 @@ export const ComboBox = <T,>(props: ComboBoxProps<T>) => {
   const inputRef = React.useRef<HTMLInputElement>(null);
   const menuRef = React.useRef<HTMLUListElement>(null);
   const toggleButtonRef = React.useRef<HTMLSpanElement>(null);
+  const firstRenderRef = React.useRef(true);
```
Comment (mayank99) [inline packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:154]: Maybe invert and rename this to something like `justMounted` or `mounted`.

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx [hunk 2]
```diff
@@ -270,14 +273,13 @@ export const ComboBox = <T,>(props: ComboBoxProps<T>) => {
...
   React.useEffect(() => {
-    if (selectedIndex != undefined && selectedIndex >= 0) {
-      const value = options[selectedIndex]?.value;
-      if (value === valueProp) {
-        return;
-      }
-      onChangeProp.current?.(value);
+    if (firstRenderRef.current) {
+      firstRenderRef.current = false;
+      return;
```
Comment (mayank99) [inline packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:278]: Do you know why this fixes the issue? Can you add a comment then?

Also add a test

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx [hunk 3]
```diff
@@ -270,14 +273,13 @@ export const ComboBox = <T,>(props: ComboBoxProps<T>) => {
 
   // Call user-defined onChange when the value actually changes
   React.useEffect(() => {
-    if (selectedIndex != undefined && selectedIndex >= 0) {
-      const value = options[selectedIndex]?.value;
-      if (value === valueProp) {
```
Comment (mayank99) [inline packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:275]: Why removed the `value === valueProp` check?

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 1 above)
Comment (gretanausedaite) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:154]: Why? What is the difference?

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 2 above)
Comment (gretanausedaite) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:278]: This solves only issue where useEffect is called on first render. It's called because combobox value is set (undefined or actual value). And we want to allow undefined value for users to reset combobox.
Will add comments.

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 3 above)
Comment (veekeys) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:275]: @mayank99 this is same as I had in multi select.
2nd use effect has the `old` value of selectedIndex!
Even though I thought if we use reducer, it should get the newest one :O

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 1 above)
Comment (veekeys) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:154]: Yeah, I think we used flag like that in somewhere else already.
@gretanausedaite `mounted` came from the original react in classes.
https://reactjs.org/docs/react-component.html#componentdidmount
so `useEffect` first call is 'almost' same as that lifecycle method in class components.

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 3 above)
Comment (mayank99) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:275]: If i remember correctly, this check was added because people were not always memoizing the onChange callback and it was leading to infinite loops 🤔 Should we use the same `queueMicrotask` logic here?

**Review by elephantcatdog — COMMENTED** [review]
I agree with Mayank on adding a test for resetting the combobox, but otherwise have no comments.

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 3 above)
Comment (veekeys) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:275]: Would be nicer if we could avoid `queueMicrotask`... Looks hacky.
Dont we add ref of `onChange` ourselves, so we dont care about users memoizing it...? Or its different

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 2 above)
Comment (gretanausedaite) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:278]: Added test to programmatically reset value.

**Review by veekeys — APPROVED** [review]

File: packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx (hunk 3 above)
Comment (mayank99) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:275]: Hmm yeah, I think `onChange` might be fine because of the ref but people also don't always memoize `options`. If you try to recreate #697 and #709 in playground, you will find that it still loops infinitely.

Comment (gretanausedaite) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:275]: I would leave `options` issue to other PR. This one fixes #697 so maybe merge?

Comment (veekeys) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:275]: But does it?
@mayank99 is saying #697 is still reproducible with your fix?

Comment (mayank99) [reply packages/iTwinUI-react/src/core/ComboBox/ComboBox.tsx:275]: yeah #697 is reproducible with current changes if `options` is not memoized
