### PR TITLE
fix(Small): Use `small` element instead of `p`

### LINKED ISSUE #734: Small: Wrong HTML tag
#### Describe the bug (actual behavior)

When `Small` is used inside another *Typography* (for example `Body`) a warning is raised:

image

#### Expected behavior

According to [HTML standards for p](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1):

> The [P](https://www.w3.org/TR/html401/struct/text.html#edef-P) element represents a paragraph. It cannot contain [block-level elements](https://www.w3.org/TR/html401/struct/global.html#block-inline) (including [P](https://www.w3.org/TR/html401/struct/text.html#edef-P) itself).

The `<Small>` component is expected to generate the `<small>` tag.

#### Reproduction
```jsx
<Body>
  Some <Small>text</Small>
</Body>
```

#### Additional information
References:
[W3C - Paragraphs: the P element](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1)
[W3C - Block-level and inline elements](https://www.w3.org/TR/html4/struct/global.html#h-7.5.3)
[MDN Content Categories](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories)
[MDN page for `small`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/small)

### PR DESCRIPTION
**Pull request by mayank99**
Fixes #734

### CODE REVIEW

File: packages/iTwinUI-react/src/core/Typography/Small/Small.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ export const Small = React.forwardRef<HTMLParagraphElement, SmallProps>(
     useTheme();
 
     return (
-      <p
+      <small
```
Comment (veekeys) [inline packages/iTwinUI-react/src/core/Typography/Small/Small.tsx:31]: Why images have changed?

File: packages/iTwinUI-react/src/core/Typography/Small/Small.tsx [hunk 2]
```diff
@@ -28,7 +28,7 @@ export const Small = React.forwardRef<HTMLParagraphElement, SmallProps>(
...
         ref={ref}
```
Comment (veekeys) [inline packages/iTwinUI-react/src/core/Typography/Small/Small.tsx:32]: Need to make same update in css demos
@FlyersPh9

**Review by veekeys — APPROVED** [review]

File: packages/iTwinUI-react/src/core/Typography/Small/Small.tsx (hunk 1 above)
Comment (mayank99) [reply packages/iTwinUI-react/src/core/Typography/Small/Small.tsx:31]: i think it's because small is an inline element, p is a block element
